### ISSUE TITLE
qzv issue

### ISSUE THREAD

**Issue by FerchoHQ** [adamovanja/qzv-viewer#1]
Hi,

I´m using this tool, I can see all my qzv files too easy, but I have an issue with 3 files:

1. demux.qzv : I can´t open this file.
2.  barplot: I only see a small figure of qiime2 logo, but not the plot.
3.  rarefactions: I can see the options for metric and sample data column, but I can´t see any option in this part. 

Note: I can see normally on https://view.qiime2.org/ 

Thanks for your time, kind regards.
![demux_qzv](https://user-images.githubusercontent.com/50809731/174876238-c64ff2a6-1d22-4173-a2ab-a83840e98358.jpg)
![barplot_qzv](https://user-images.githubusercontent.com/50809731/174876253-fa31abd8-f8c5-46c8-81c1-c04aca7456af.jpg)
![rarefactions_qzv](https://user-images.githubusercontent.com/50809731/174876265-b135e03a-49d7-4454-bd71-0ec85c3a2813.jpg)

**Comment by adamovanja** [comment]
Hi there, 

Thanks for giving this package a try. Yes, as you have found correctly that there are still output visualizations which are not correctly displayed with the qzv-viewer. 

However, since you are using Jupyter notebooks, there is another working QIIME 2 notebook extension out there (unrelated to qzv-viewer). You can install it by running the following command in your terminal before opening the Jupyter interface:
```
jupyter serverextension enable --py qiime2 --sys-prefix
```
After opening the jupyter notebook with `jupyter notebook`, you can display all QIIME 2 visualizations inline with the following commands:
```
from qiime2 import Visualization
Visualization.load(<INSERT_PATH2FILE>)
```

I hope this helps.

**Comment by FerchoHQ** [comment]
Hi,

Thank you so much for your help, I'll use this information.

Kind regards.

**Comment by adamovanja** [comment]
P.S. for the above command (`jupyter serverextension enable --py qiime2 --sys-prefix`) to run, you need to install another conda package with `conda install jupyter_contrib_nbextensions`
